const $=id=>document.getElementById(id);
async function api(path,options={}){const response=await fetch('/api'+path,{credentials:'same-origin',...options});let data;try{data=await response.json()}catch{data={error:'Service unavailable.'}}if(!response.ok)throw Error(data.error||'Request failed.');return data}
function status(id,message,error=false){const el=$(id);if(el){el.textContent=message;el.classList.toggle('error',error)}}
function article(item){const wrapper=document.createElement('article');wrapper.className='list-item';const h=document.createElement('h3');h.textContent=item.title;wrapper.append(h);const date=document.createElement('small');date.textContent=new Date(item.published_at).toLocaleDateString('en-NG',{dateStyle:'medium'});wrapper.append(date);const p=document.createElement('p');p.textContent=item.body;wrapper.append(p);return wrapper}
async function listing(section,target,notice){try{const {items}=await api('/content?section='+encodeURIComponent(section));$(target).replaceChildren(...items.map(article));if(!items.length)status(notice,'No updates have been posted yet.');else status(notice,'')}catch(e){status(notice,e.message,true)}}
async function login(form,notice){const v=Object.fromEntries(new FormData(form));try{await api('/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(v)});location.reload()}catch(e){status(notice,e.message,true)}}
async function gate(role,content,notice){try{const {user}=await api('/me');if(user&&(user.role===role||user.role==='admin')){$(content).classList.remove('hidden');$('login-panel')?.classList.add('hidden');return true}status(notice,'Sign in with your '+role+' account to view this page.');return false}catch(e){status(notice,e.message,true);return false}}
document.addEventListener('submit',async event=>{const form=event.target;if(!form.matches('[data-login]'))return;event.preventDefault();await login(form,form.dataset.notice)});
document.addEventListener('click',async event=>{if(event.target.matches('[data-logout]')){await api('/logout',{method:'POST'});location.href='/'}});
